### ISSUE TITLE
Inline formatting menu "link" button does nothing in Firefox

### ISSUE THREAD

**Issue by linc** [vanilla/rich-editor#105]
On the staff forum while writing a post, I highlighted 3 words in the middle of a paragraph sentence and the inline formatting menu appeared. I clicked the last option, the link icon, and that caused the menu to disappear. Nothing further happened. Repeating the tasks had the same outcome each time.

Firefox 61

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/rich-editor/pull/107
