### ISSUE TITLE
Inline Menu - Keep open after styling

### ISSUE THREAD

**Issue by slafleche** [vanilla/rich-editor#19]
The inline menu shows up when you have selected text and should remain open if you select an option from the inline menu. It's weird to need to reselect it. The user may want to select bold and italic in one shot. It may also be confusing to not see the menu anymore.

**Comment by charrondev** [comment]
> From @tburry 
> ## Selected text should always show the inline formatting menu
> 
> When I have a text selection (in one paragraph?) then the inline formatting menu should always be open. It should not close when I select a format.
> 
> ### Steps to reproduce
> 
> 1. Select some text.
> 2. Select bold.
> 3. Notice the menu closes, even though the text is still selected. It should instead remain open.
> 
> This also dovetails with a conversation we had earlier. Perhaps selecting multiple paragraphs opens the paragraph menu or at least makes it available.

**Comment by charrondev** [comment]
## Final success criteria:

- The inline formatting menu is __always__ open if:
  - The editor has a selection with a length > 0
  - That selection does __not__ span multiple lines (1 line only).
  - The editor has focus __or__ something in the inline menu has focus.
- Formatting an item with the inline menu should __not__ close the menu.
- The paragraph formatting menu is available with selections that span multiple lines.
