### ISSUE TITLE
Rich Editor - Refactor Flyout components

### ISSUE THREAD

**Issue by slafleche** [vanilla/rich-editor#24]
Our flyouts are pretty complicated and hard to understand currently. We should do some refactoring. I like the way we handled the flyouts in our base theme prototype. The "dropdown" component takes 2 components, 1 for the contents of the toggle button and the other for the contents of the flyout. 

It's true that our flyouts aren't always that style in the editor. We've got some special positioning, but I think we can simplify

**Comment by charrondev** [comment]
Closing this as we've already refactored these menus.
