### ISSUE TITLE
Improve paragraph menu icon positioning and active states

### ISSUE THREAD

**Issue by slafleche** [vanilla/rich-editor#33]
It's not really useful to have the plain paragraph style be the first option in the paragraph menu. Let's bump it to the last element on the list.

Since it also behaves differently than the rest of the styles, we should either disable it or hide it when it is plain text. If we take the heading for example, clicking the heading once makes it a heading, hitting it again removes the heading. The paragraph doesn't "undo" like the other styles, so it should be handled differently.

**Comment by charrondev** [comment]
I'm closing this right now. @tburry Has some enhanced mockups that account for this case.

In the meantime, I've already updated the menu to behave like a proper radio-list.
