### ISSUE TITLE
Url Embed - submit doesn't disable after we post an embed

### ISSUE THREAD

**Issue by slafleche** [vanilla/rich-editor#46]
When you load the page, the "insert" button is disabled. It gets enabled if you put in a valid url. However, if you open the flyout again, it doesn't get reset to be disabled.

**Comment by charrondev** [comment]
Issue moved to [vanilla/vanilla #7598](https://github.com/vanilla/vanilla/issues/7598) via [**ZenHub**](https://www.zenhub.com/)
