### ISSUE TITLE
Test Email Notifications from Rich Editor Posts

### ISSUE THREAD

**Issue by slafleche** [vanilla/rich-editor#92]
We never did any testing with e-mail notifications from rich editor posts.

@adrianspeyer reported an issue with images leaving big gaps... We may need a simplified rendering of embeds for e-mails.

**Comment by charrondev** [comment]
Issue moved to [vanilla/vanilla #7592](https://github.com/vanilla/vanilla/issues/7592) via [**ZenHub**](https://www.zenhub.com/)
