### ISSUE TITLE
Make list a code block style

### ISSUE THREAD

**Issue by slafleche** [vanilla/rich-editor#94]
It makes intuitive sense to write up multiple lines, select them and then try to convert them to a list. We should add that option to the paragraph menu.

It would also make sense to also allow "*" to make lists, like we do for "-"

**Comment by linc** [comment]
Note that currently you cannot select multiple lines and then choose block-level formatting, so that's another challenge.

**Comment by charrondev** [comment]
This has been resolved

**Comment by linc** [comment]
> This has been resolved

Howso?
