### ISSUE TITLE
"format" on <textarea/> is invalid HTML

### ISSUE THREAD

**Issue by slafleche** [vanilla/rich-editor#96]
I would like, moving forward, that all our HTML passes W3C validation. I noticed that vanilla uses a non standard "format" attribute on textareas. This is invalid HTML. Any custom attributes need to be prefixed with "data".

**Comment by charrondev** [comment]
Issue moved to [vanilla/vanilla #7591](https://github.com/vanilla/vanilla/issues/7591) via [**ZenHub**](https://www.zenhub.com/)
